### ISSUE TITLE
Dupery - Hair #34 crashes game on dupe spawn.

### ISSUE THREAD

**Issue by Ashotep** [Barleytree/Dupery#7]
When creating a dupe using hair 34 the game will crash when that dupe is spawned.  It references an "unknown asset"  It isn't the hard crash that the game then tries to disable the mod but a soft one where the game doesn't recommend disabling the mod.  I no longer have the logs for the crash.  This happened a few days ago and I forgot about it after I found the issue.  If you need the logs I can recreate the crash and upload them if needed.

**Comment by Ashotep** [comment]
I there a way to view the table that is created with the various personality types (ie. hair, body, etc.)  Not what is custom added via a .json file but the initial pool the mod creates when it query's the game for hathair, etc.  

I've started to notice inconsistencies with some of the default hairs and their corresponding number.  IE. hair 34 is actually hair 36 now.  34 will crash the game if it tries to spawn.  I don't know if they are saving a placeholder in their code or it detects the unique hair of the hermit and telling the game it's invalid.  Either way, to fix the guide an inspection of what is assigned what number is needed.

**Comment by WoodyPampa** [comment]
If you still didn't found solution, then this will help you maybe.

![68747470733a2f2f692e696d6775722e636f6d2f6d476b594d66422e706e67](https://github.com/Barleytree/Dupery/assets/76798400/30c4de4c-84b8-4dcc-8736-d3c9cbfe6318)

Just in case, there is a missing eye, who is number 6, it's the same eye from the Dup Steve with Hair 44.
If you are using other value, then sometime it will crash, or sometime it will swap with the default value, for the hair for example it's 1.
Hope it help


The Hair_ Tag is for the Cassidy Dup from "Print Cassidy" mod, from the author of Dupery, and the other are from Voiceroid Mod
, so without the associated Mod, they will not work.

**Comment by Ashotep** [comment]
I absolutely love that you just pointed out the solution with the chart that I personally created.

I noticed this issue, did some testing, sat down and personally mapped out each hairstyle body type etc to what namber/name. Then taught myself how to Photoshop and create the chart above. That I then donated it back to the mod author and the community for other people to reference.

This made my day.

**Comment by WoodyPampa** [comment]
Atcha... I didn't notice that the topic was closed :/ sorry

Well, I'm happy that you are too :p

What I said about Eye 6 remain true if you want to make a refresh of the image ^^.

I use this opportunity to ask if you found each part, body, eyes, hair etc in a specific folder of the game, or did you use Photoshop for everything ?
I'm asking because I was thinking about sharing a little mod with many custom Dup, but when we go in the Supply Clost of Duplicant, we have a white square for each custom Dup and I would like to give them something like the vanilla Dups on this Tab.

**Comment by Ashotep** [comment]
It was a huge process. I had to unpack the game look at every single asset to find the correct style etc. I then had to copy that asset into gimp manually lay it out label it etc. This was just the process after I had already mapped it out and done my testing

Keep in mind that I had zero experience with any of the programs and what to do from the start and basically had to teach myself as I went. I did know about the number six, but intentionally left it off because it's not completely compatible... At least at the time I haven't played the game in a while. And certain combinations would crash the game.

All in all it took  about 2 days of my time one weekend. All because I was annoyed I didn't have a certain combination that I wanted because it was off. Once I finished I was pleased with the result decide to share it.

**Comment by WoodyPampa** [comment]
(I'm trying to use the direct reply from my mail box, not sure if that
really work or not)

I see, that was a very tedious experience for you to reverse engineer all
of this.

Well, thanks for your time and work with this nice and useful image, I'm
sure that it already helped a lot of people like me, and helped to avoid
the brute force method to customize our little Dups.
Like you I have no XP with Oni modding or programing and stuff like that,
but I have a lot with Photoshop, Gimp and other software like them, I'm
kind of an advanced user of these software, if I can put it that way. ^^'

And so...
I doesn't want to bother you, but, if by any chance you still have some
archive of your work, or maybe just the name of the Dups assets, anything
who could help me, can you think about the possibility to share this with
me ?
I wish I could share a finished and attractive mod, not just a plain text
file filled with white squares everywhere when people want to use the new
outfit feature to customize their Dups with...
I would really appreciate but maybe you didn't keep anything or forget
where it can be, it's not a big deal if that the case, I'm loosing archives
all the time so I'm used to this ^^'
But if you still have it, or found where it was, and are ok to share it
with me it would be amazing and save me a lot of time.
But don't rush it, take your time, there is no hurry, I'm just trying my
luck with asking  :p


At first it was just for my personal use, like you I wanted to have some
specific combinations that wasn't available in the game, so...
I did some test about combinations, I used Notepad++ and run a little
script (with the help of OpenAI  because I don't know anything about
coding), and then I was able to add every possibility of combination on the
.Json, I don't remember how many Dups there was, but it was a LOT!  0_0'
Hopefully the script was giving random name for all of them, I didn't have
to do it myself
And you was right, I can confirm that some of them may crash the game, at
least it still the case today.

Ho, and about the Eye 6, if you come back to the game one day, eye 6 are ok
with everything from the vanilla game.

The thing that I didn't tested was about custom Hair from "Voiceroid" or
"So Many Dupes" because Barley stated on the Dupery Mod page that it can
potently make a save unplayable after a game update, so I preferred to
forget about theses for the moment.
I'm just taking the risk for Cassidy ^^

Whatever you choose, between sharing something or not, I will still credit
you on my mod page (if I'm able to finish my project of course) because
without your work I would maybe not even try to custom my Dup and not test
all I did, I'm sure about that.
But if for any reason you prefer to doesn't be mentioned I will respect
your choice, tell me please if it's ok for you or not.

I let you think about all of this and have a nice night/day, I have to
sleep and things to do.
Thanks again for your time
